name: 'Create Release PR'
description: 'An action to create release PRs'

# Define your inputs here.
inputs:
  mainBranch:
    description: 'main branch to PR release into'
    required: false
    default: main
  releaseBranch:
    description: 'name of the release branch to release from'
    required: true
  token:
    description: 'GitHub token for creating and grooming release PRs, defaults to using secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  repo-url:
    description: 'configure github repository URL. Default `process.env.GITHUB_REPOSITORY`'
    required: false
    default: ''

# Define your outputs here.
outputs: { }

runs:
  using: node20
  main: dist/index.js
