---
name: build loki image
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 8 * * *" # daily at 8am, but how to specify branch name?
  push:
    branches:
      - "main"
      - "release-[0-9].[0-9].x"
      - "k[0-9]*"

jobs:
  loki-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm
    steps:
      - name: pull loki code
        uses: actions/checkout@v3
        with:
          repository: grafana/loki
          ref: prepare-release-please
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.3"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: parse image metadata
        id: parse-metadata
        shell: bash
        run: |
          mkdir -p dist

          platform="$(echo "${{ matrix.platform}}" |  sed  "s/\(.*\)\/\(.*\)/\1-\2/")"
          echo "platform=${platform}" >> $GITHUB_OUTPUT

          version=$(jq -r '."cmd/loki"' .release-please-manifest.json)
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: cmd/loki/Dockerfile
          platforms: ${{ matrix.platform }}
          tags: grafana/loki:${{ steps.parse-metadata.outputs.version }}
          outputs: type=docker,dest=dist/loki-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: loki-image-${{ matrix.platform }}
          path: dist/loki-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar
