"jobs":
  "check":
    "container":
      "image": "grafana/loki-build-image"
      "volumes":
      - ".:/src/loki"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull loki code"
      "uses": "actions/checkout@v3"
      "with":
        "ref": "prepare-release-please"
        "repository": "grafana/loki"
    - "name": "setup go"
      "uses": "actions/setup-go@v4"
      "with":
        "go-version-file": "go.mod"
    - "name": "check generated files"
      "run": "make BUILD_IN_CONTAINER=false check-generated-files"
    - "name": "check mod"
      "run": "make BUILD_IN_CONTAINER=false check-mod"
    - "name": "shellcheck"
      "run": "make BUILD_IN_CONTAINER=false lint-scripts"
    - "name": "check docs"
      "run": "make BUILD_IN_CONTAINER=false check-doc"
    - "name": "validate example configs"
      "run": "make BUILD_IN_CONTAINER=false check-example-config-doc"
    - "name": "check helm reference doc"
      "run": "make BUILD_IN_CONTAINER=false documentation-helm-reference-check"
  "lint":
    "container":
      "image": "grafana/loki-build-image"
      "volumes":
      - ".:/src/loki"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull loki code"
      "uses": "actions/checkout@v3"
      "with":
        "ref": "prepare-release-please"
        "repository": "grafana/loki"
    - "name": "setup go"
      "uses": "actions/setup-go@v4"
      "with":
        "go-version-file": "go.mod"
    - "name": "lint"
      "run": "make BUILD_IN_CONTAINER=false lint"
    - "name": "lint jsonnet"
      "run": "make BUILD_IN_CONTAINER=false lint-jsonnet"
  "loki-image":
    "needs":
    - "test"
    - "lint"
    - "check"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull loki code"
      "uses": "actions/checkout@v3"
      "with":
        "ref": "prepare-release-please"
        "repository": "grafana/loki"
    - "name": "Set up QEMU"
      "uses": "docker/setup-qemu-action@v3"
      "with":
        "go-version-file": "go.mod"
    - "name": "set up docker buildx"
      "uses": "docker/setup-buildx-action@v3"
    - "id": "parse-metadata"
      "name": "parse image metadata"
      "run": |
        mkdir -p dist
        
        platform="$(echo "${{ matrix.platform}}" |  sed  "s/\(.*\)\/\(.*\)/\1-\2/")"
        echo "platform=${platform}" >> $GITHUB_OUTPUT
        
        version=$(jq -r '."cmd/loki"' .release-please-manifest.json)
        echo "version=${version}" >> $GITHUB_OUTPUT
      "shell": "bash"
    - "name": "Build and export"
      "uses": "docker/build-push-action@v5"
      "with":
        "context": "."
        "file": "cmd/loki/Dockerfile"
        "outputs": "type=docker,dest=dist/loki-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
        "platforms": "${{ matrix.platform }}"
        "tags": "grafana/loki:${{ steps.parse-metadata.outputs.version }}"
    - "name": "upload artifacts"
      "uses": "actions/upload-artifact@v3"
      "with":
        "name": "loki-image-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}"
        "path": "dist/loki-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
    "strategy":
      "fail-fast": true
      "matrix":
        "platform":
        - "linux/amd64"
        - "linux/arm64"
        - "linux/arm"
  "promtail-image":
    "needs":
    - "test"
    - "lint"
    - "check"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull loki code"
      "uses": "actions/checkout@v3"
      "with":
        "ref": "prepare-release-please"
        "repository": "grafana/loki"
    - "name": "Set up QEMU"
      "uses": "docker/setup-qemu-action@v3"
      "with":
        "go-version-file": "go.mod"
    - "name": "set up docker buildx"
      "uses": "docker/setup-buildx-action@v3"
    - "id": "parse-metadata"
      "name": "parse image metadata"
      "run": |
        mkdir -p dist
        
        platform="$(echo "${{ matrix.platform}}" |  sed  "s/\(.*\)\/\(.*\)/\1-\2/")"
        echo "platform=${platform}" >> $GITHUB_OUTPUT
        
        version=$(jq -r '."clients/cmd/promtail"' .release-please-manifest.json)
        echo "version=${version}" >> $GITHUB_OUTPUT
      "shell": "bash"
    - "name": "Build and export"
      "uses": "docker/build-push-action@v5"
      "with":
        "context": "."
        "file": "clients/cmd/promtail/Dockerfile"
        "outputs": "type=docker,dest=dist/promtail-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
        "platforms": "${{ matrix.platform }}"
        "tags": "grafana/promtail:${{ steps.parse-metadata.outputs.version }}"
    - "name": "upload artifacts"
      "uses": "actions/upload-artifact@v3"
      "with":
        "name": "promtail-image-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}"
        "path": "dist/promtail-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
    "strategy":
      "fail-fast": true
      "matrix":
        "platform":
        - "linux/amd64"
        - "linux/arm64"
        - "linux/arm"
  "test":
    "container":
      "image": "grafana/loki-build-image"
      "volumes":
      - ".:/src/loki"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull loki code"
      "uses": "actions/checkout@v3"
      "with":
        "ref": "prepare-release-please"
        "repository": "grafana/loki"
    - "name": "setup go"
      "uses": "actions/setup-go@v4"
      "with":
        "go-version-file": "go.mod"
    - "name": "test"
      "run": "make BUILD_IN_CONTAINER=false test"
"name": "release (jsonnet version)"
"on":
  "push":
    "branches":
    - "main"
    - "release-[0-9].[0-9].x"
    - "k[0-9]*"
  "workflow_dispatch": {}
"permissions":
  "contents": "write"
  "issues": "write"
  "pull-requests": "write"
