---
name: prepare release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # daily at 8am
  push:
    branches:
      - "release-[0-9].[0-9].x"

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "validating code"
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "building code"
  upload:
    runs-on: ubuntu-latest
    needs:
      - validate
      - build
    steps:
      - run: |
          echo "uploading release artifacts"
  release-please:
    runs-on: ubuntu-latest
    needs:
      - upload
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
