---
name: 'create release'
on:
  push:
    branches:
      - 'main'
      - 'release-[0-9].[0-9].x'
      - 'k[0-9]*'
  workflow_dispatch: {}
permissions:
  contents: 'write'
  issues: 'write'
  pull-requests: 'write'
jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      release_repo: grafana/loki-release
      release_pr_workflow: release-pr-local.yml
