---
name: prepare release
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 8 * * *" # daily at 8am, but how to specify branch name?
  push:
    branches:
      - "main"
      - "release-[0-9].[0-9].x"
      - "k[0-9]*"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: validate
        run: |
          echo "validating code"
      - name: build artifacts
        run: |
          mkdir -p dist
          echo "building code" > dist/build.txt
      - name: extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          default-branch: "${{ steps.extract_branch.outputs.branch }}"
          versioning: always-bump-patch
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/build.txt
      # TODO: announce in #loki-releases if release created
