jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
    - name: "always green"
      run: "echo \"always green\""
      shell: "bash"
  dist:
    needs:
    - "test"
    - "lint"
    - "check"
    runs-on: "ubuntu-latest"
    steps:
    - name: "pull loki code"
      uses: "actions/checkout@v3"
      with:
        path: "loki"
        ref: "prepare-release-please"
        repository: "grafana/loki"
    - name: "setup go"
      uses: "actions/setup-go@v4"
      with:
        cache-dependency-path: "loki/go.sum"
        go-version-file: "loki/go.mod"
    - name: "install dependencies"
      run: |
        go install github.com/mitchellh/gox@9f71238
        go install github.com/bufbuild/buf/cmd/buf@v1.4.0
        go install github.com/golang/protobuf/protoc-gen-go@v1.3.1
        go install github.com/gogo/protobuf/protoc-gen-gogoslick@v1.3.0
        
        sudo apt update
        sudo apt install -qy musl gnupg ragel \
          file zip unzip jq gettext \
          protobuf-compiler libprotobuf-dev \
          libsystemd-dev jq
      shell: "bash"
    - name: "build artifacts"
      run: "make BUILD_IN_CONTAINER=false dist"
      shell: "bash"
      working-directory: "loki"
    - name: "upload artifacts"
      uses: "actions/upload-artifact@v3"
      with:
        name: "dist"
        path: "lok/dist/"
  lint:
    runs-on: "ubuntu-latest"
    steps:
    - name: "always green"
      run: "echo \"always green\""
      shell: "bash"
  loki-image:
    needs:
    - "test"
    - "lint"
    - "check"
    runs-on: "ubuntu-latest"
    steps:
    - name: "pull loki code"
      uses: "actions/checkout@v3"
      with:
        path: "loki"
        ref: "prepare-release-please"
        repository: "grafana/loki"
    - name: "setup go"
      uses: "actions/setup-go@v4"
      with:
        cache-dependency-path: "loki/go.sum"
        go-version-file: "loki/go.mod"
    - name: "Set up QEMU"
      uses: "docker/setup-qemu-action@v3"
    - name: "set up docker buildx"
      uses: "docker/setup-buildx-action@v3"
    - id: "parse-metadata"
      name: "parse image metadata"
      run: |
        mkdir -p dist
        
        platform="$(echo "${{ matrix.platform}}" |  sed  "s/\(.*\)\/\(.*\)/\1-\2/")"
        echo "platform=${platform}" >> $GITHUB_OUTPUT
        
        version=$(jq -r '."cmd/loki"' .release-please-manifest.json)
        echo "version=${version}" >> $GITHUB_OUTPUT
      shell: "bash"
      working-directory: "loki"
    - name: "Build and export"
      uses: "docker/build-push-action@v5"
      with:
        context: "loki"
        file: "loki/cmd/loki/Dockerfile"
        outputs: "type=docker,dest=loki/dist/loki-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
        platforms: "${{ matrix.platform }}"
        tags: "grafana/loki:${{ steps.parse-metadata.outputs.version }}"
    - name: "upload artifacts"
      uses: "actions/upload-artifact@v3"
      with:
        name: "loki-image-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}"
        path: "loki/dist/loki-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
    strategy:
      fail-fast: true
      matrix:
        platform:
        - "linux/amd64"
        - "linux/arm64"
        - "linux/arm"
  promtail-image:
    needs:
    - "test"
    - "lint"
    - "check"
    runs-on: "ubuntu-latest"
    steps:
    - name: "pull loki code"
      uses: "actions/checkout@v3"
      with:
        path: "loki"
        ref: "prepare-release-please"
        repository: "grafana/loki"
    - name: "setup go"
      uses: "actions/setup-go@v4"
      with:
        cache-dependency-path: "loki/go.sum"
        go-version-file: "loki/go.mod"
    - name: "Set up QEMU"
      uses: "docker/setup-qemu-action@v3"
    - name: "set up docker buildx"
      uses: "docker/setup-buildx-action@v3"
    - id: "parse-metadata"
      name: "parse image metadata"
      run: |
        mkdir -p dist
        
        platform="$(echo "${{ matrix.platform}}" |  sed  "s/\(.*\)\/\(.*\)/\1-\2/")"
        echo "platform=${platform}" >> $GITHUB_OUTPUT
        
        version=$(jq -r '."clients/cmd/promtail"' .release-please-manifest.json)
        echo "version=${version}" >> $GITHUB_OUTPUT
      shell: "bash"
      working-directory: "loki"
    - name: "Build and export"
      uses: "docker/build-push-action@v5"
      with:
        context: "loki"
        file: "loki/clients/cmd/promtail/Dockerfile"
        outputs: "type=docker,dest=loki/dist/promtail-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
        platforms: "${{ matrix.platform }}"
        tags: "grafana/promtail:${{ steps.parse-metadata.outputs.version }}"
    - name: "upload artifacts"
      uses: "actions/upload-artifact@v3"
      with:
        name: "promtail-image-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}"
        path: "loki/dist/promtail-${{ steps.parse-metadata.outputs.version}}-${{ steps.parse-metadata.outputs.platform }}.tar"
    strategy:
      fail-fast: true
      matrix:
        platform:
        - "linux/amd64"
        - "linux/arm64"
        - "linux/arm"
  release:
    needs:
    - "dist"
    - "loki-image"
    - "promtail-image"
    runs-on: "ubuntu-latest"
    steps:
    - name: "pull loki code"
      uses: "actions/checkout@v3"
      with:
        path: "loki"
        ref: "prepare-release-please"
        repository: "grafana/loki"
    - name: "pull release code"
      uses: "actions/checkout@v3"
      with:
        path: "release"
        repository: "grafana/loki-release"
    - name: "setup go"
      uses: "actions/setup-go@v4"
      with:
        cache-dependency-path: "loki/go.sum"
        go-version-file: "loki/go.mod"
    - name: "setup node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 16
    - id: "extract_branch"
      name: "extract branch name"
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: "bash"
      working-directory: "loki"
    - id: "release"
      name: "release please"
      run: |
        npm install
        npm exec -- release-please release-pr --token="${{ secrets.GITHUB_TOKEN }}" --repo-url="grafana/loki-release" --label "backport ${{ steps.extract_branch.outputs.branch}}" --manifest-file release/release-please-config.json
      shell: "bash"
      working-directory: "loki"
    - if: "${{ steps.release.outputs.release_created }}"
      name: "download dist"
      uses: "actions/download-artifact@v3"
      with:
        name: "dist"
        path: "release/dist/"
    - env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: "${{ steps.release.outputs.release_created }}"
      name: "upload release artifacts"
      run: |
        gh release upload ${{ steps.release.outputs.tag_name }} ./dist/build.txt
      shell: "bash"
      working-directory: "loki"
    - id: "update_release_config"
      if: "${{ startsWith(steps.extract_branch.outputs.branch, 'k') && steps.release.outputs.release_created }}"
      name: "create release branch from k release"
      run: |
        branch=release-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.x
        git checkout -b $branch
        mv release-please-config.json tmp.json
        jq '.versioning = "always-bump-patch"' tmp.json > release-please-config.json
        rm tmp.json
      shell: "bash"
      working-directory: "loki"
    - id: "create_release_branch"
      if: "${{ steps.update_release_config.outcome == 'success' }}"
      name: "commit changes to release branch"
      uses: "stefanzweifel/git-auto-commit-action@v5"
      with:
        branch: "release-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.x"
        commit_message: "chore: release branch bumps patch on release"
        create_branch: true
        file_pattern: "loki/release-please-config.json"
    - env:
        BRANCH: "release-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.x"
      id: "created_branch_message"
      if: "${{ steps.create_release_branch.outcome == 'success' }}"
      name: "comment on PR with release branch"
      run: |
        prNumber=$(echo ${{ steps.release.outputs.pr }} | jq -r .number)
        gh pr comment $prNumber --body "created release branch [$BRANCH](https://github.com/grafana/loki-release/tree/$BRANCH)"
      shell: "bash"
      working-directory: "loki"
  test:
    runs-on: "ubuntu-latest"
    steps:
    - name: "always green"
      run: "echo \"always green\""
      shell: "bash"
name: "release"
"on":
  push:
    branches:
    - "main"
    - "release-[0-9].[0-9].x"
    - "k[0-9]*"
  workflow_dispatch: {}
permissions:
  contents: "write"
  issues: "write"
  pull-requests: "write"
