---
name: 'create release'
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read
jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      release_repo: grafana/loki-release
      release_pr_workflow: release-pr-local.yml
    secrets:
      GCS_SERVICE_ACCOUNT_KEY: '${{ secrets.BACKEND_ENTERPRISE_DRONE }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
