concurrency:
  group: "create-release-${{ github.sha }}"
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
    - name: "pull loki code"
      uses: "actions/checkout@v3"
      with:
        path: "loki"
        ref: "prepare-release-please"
        repository: "grafana/loki"
    - name: "pull release code"
      uses: "actions/checkout@v3"
      with:
        path: "release"
        repository: "grafana/loki-release"
    - name: "setup node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 16
    - env:
        ACTIONS_STEP_DEBUG: "true"
      id: "auth"
      name: "auth gcs"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.BACKEND_ENTERPRISE_DRONE }}"
    - env:
        ACTIONS_STEP_DEBUG: "true"
      name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"
      with:
        version: ">= 452.0.0"
    - name: "download build artifacts"
      run: |
        gsutil cp gs://loki-build-artifacts/${{ github.sha }}/dist.tar.gz .
        tar -xzf dist.tar.gz dist
        ls dist
      shell: "bash"
      working-directory: "release"
name: "create release"
"on":
  workflow_call:
    inputs:
      release_pr_workflow:
        default: "release-pr.yml"
        description: "workflow file that created the release pr"
        required: false
        type: "string"
      release_repo:
        default: "grafana/loki"
        description: "repo to make release in"
        required: false
        type: "string"
permissions:
  contents: "write"
  issues: "write"
  pull-requests: "write"
