name: Abuse Input Test

on:
  workflow_dispatch:

jobs:
  abuse-test:
    uses: grafana/loki-release/.github/workflows/check.yml@main
    with:
      skip_validation: " true "
      use_github_app_token: true
      build_image: malicious/image
    secrets: inherit

  post-check:
    runs-on: ubuntu-latest
    needs: abuse-test
    steps:
      - name: Confirm Inputs Passed
        run: |
          echo "Logging input abuse test..."
          echo "::notice ::SKIP_VALIDATION set to: 'true'"
          echo "::notice ::USE_GITHUB_APP_TOKEN is enabled"
          echo "::notice ::BUILD_IMAGE set to: 'malicious/image'"
